---
title: "Gesture_Signatures"
author: "Sam Voisin"
date: "4/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## EMG Data Gesture Signatures

The intent of this document is to visualize the signatures of the gestures encoded by EMG data. Our hypothesis is that each gesture may tend toward a unique signature that can be identified algorithmically.

```{r libraries, echo = FALSE, message = FALSE, warning = FALSE}

library(tidyr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(here)

```


```{r data, echo=FALSE}

# root file directory for data files
rootname <- "../EMG_data_for_gestures-master/"
rootname2 <- "../clean_EMG_data_for_gestures-master/"

# data file references for subjects 01, 11, 21, 31
fnames <- c(paste0(rootname, "01/1_raw_data_13-12_22.03.16.txt"),
            paste0(rootname, "11/1_raw_data_13-11_18.03.16.txt"),
            paste0(rootname, "21/1_raw_data_20-28_24.04.16.txt"),
            paste0(rootname, "31/1_raw_data_11-15_11.04.16.txt"))

# read in data tables
subj01 <- read.table(fnames[1], header = TRUE)
subj11 <- read.table(fnames[2], header = TRUE)
subj21 <- read.table(fnames[3], header = TRUE)
subj31 <- read.table(fnames[4], header = TRUE)

# data file references for subjects 01, 11, 21, 31
fnames_clean <- c(paste0(rootname2, "01/1_clean_data_13-12_22.03.16.txt"),
                  paste0(rootname2, "11/1_clean_data_13-11_18.03.16.txt"),
                  paste0(rootname2, "21/1_clean_data_20-28_24.04.16.txt"),
                  paste0(rootname2, "31/1_clean_data_11-15_11.04.16.txt"))

# read in data tables
subj01_clean <- read.table(fnames_clean[1], header = TRUE)
subj11_clean <- read.table(fnames_clean[2], header = TRUE)
subj21_clean <- read.table(fnames_clean[3], header = TRUE)
subj31_clean <- read.table(fnames_clean[4], header = TRUE)

gestclasses <- seq(1, 8)

```


```{r plotfcn, echo = FALSE}

# helper function for plotting gestures

plot_gest_sig <- function(subjdf, gestnum, subjnum, timecut) {
  # plot a single gesture over time
  
  p1 <- subjdf %>% 
    filter(class == gestnum) %>%
    filter(time < timecut) %>% 
    gather(key = "channel", value = "EMG_Measure", -time, -class) %>%
    ggplot(aes(x = time, y = EMG_Measure, color = channel)) + 
    ggtitle(paste0("Subject ", subjnum, ": Gesture ", gestnum)) +
    labs(x = "Time (ms)", y = "EMG Reading") +
    geom_point()
    
  p2 <- subjdf %>% 
    filter(class == gestnum) %>%
    filter(time > timecut) %>% 
    gather(key = "channel", value = "EMG_Measure", -time, -class) %>%
    ggplot(aes(x = time, y = EMG_Measure, color = channel)) + 
    ggtitle(paste0("Subject ", subjnum, ": Gesture ", gestnum)) +
    labs(x = "Time (ms)", y = "EMG Reading") +
    geom_point()
  
  grid.arrange(p1, p2)
  
}

```

## Subject 01

```{r subject01, echo = FALSE}


plot_gest_sig(subj01, 1, "01", 5000)
plot_gest_sig(subj01, 2, "01", 10000)
plot_gest_sig(subj01, 3, "01", 20000)
plot_gest_sig(subj01, 4, "01", 25000)
plot_gest_sig(subj01, 5, "01", 30000)
plot_gest_sig(subj01, 6, "01", 35000)

```


```{r subject01clean, echo = FALSE}

plot_gest_sig(subj01_clean, 1, "01", 5000)
plot_gest_sig(subj01_clean, 2, "01", 10000)
plot_gest_sig(subj01_clean, 3, "01", 20000)
plot_gest_sig(subj01_clean, 4, "01", 25000)
plot_gest_sig(subj01_clean, 5, "01", 30000)
plot_gest_sig(subj01_clean, 6, "01", 35000)

```

## Subject 11

```{r subject11, echo = FALSE}

plot_gest_sig(subj11, 1, "11", 5000)
plot_gest_sig(subj11, 2, "11", 10000)
plot_gest_sig(subj11, 3, "11", 20000)
plot_gest_sig(subj11, 4, "11", 25000)
plot_gest_sig(subj11, 5, "11", 30000)
plot_gest_sig(subj11, 6, "11", 35000)

```



```{r subject11clean, echo = FALSE}

plot_gest_sig(subj11_clean, 1, "11", 5000)
plot_gest_sig(subj11_clean, 2, "11", 10000)
plot_gest_sig(subj11_clean, 3, "11", 20000)
plot_gest_sig(subj11_clean, 4, "11", 25000)
plot_gest_sig(subj11_clean, 5, "11", 30000)
plot_gest_sig(subj11_clean, 6, "11", 35000)

```

## Subject 21

```{r subject21, echo = FALSE}

plot_gest_sig(subj21, 1, "21", 5000)
plot_gest_sig(subj21, 2, "21", 10000)
plot_gest_sig(subj21, 3, "21", 20000)
plot_gest_sig(subj21, 4, "21", 25000)
plot_gest_sig(subj21, 5, "21", 30000)
plot_gest_sig(subj21, 6, "21", 35000)


```



```{r subject21clean, echo = FALSE}

plot_gest_sig(subj21_clean, 1, "21", 5000)
plot_gest_sig(subj21_clean, 2, "21", 10000)
plot_gest_sig(subj21_clean, 3, "21", 20000)
plot_gest_sig(subj21_clean, 4, "21", 25000)
plot_gest_sig(subj21_clean, 5, "21", 30000)
plot_gest_sig(subj21_clean, 6, "21", 35000)

```

## Subject 31

```{r subject31, echo = FALSE}

plot_gest_sig(subj31, 1, "31", 5000)
plot_gest_sig(subj31, 2, "31", 10000)
plot_gest_sig(subj31, 3, "31", 20000)
plot_gest_sig(subj31, 4, "31", 25000)
plot_gest_sig(subj31, 5, "31", 30000)
plot_gest_sig(subj31, 6, "31", 35000)

```


```{r subject31clean, echo = FALSE}

plot_gest_sig(subj31_clean, 1, "31", 5000)
plot_gest_sig(subj31_clean, 2, "31", 10000)
plot_gest_sig(subj31_clean, 3, "31", 20000)
plot_gest_sig(subj31_clean, 4, "31", 25000)
plot_gest_sig(subj31_clean, 5, "31", 30000)
plot_gest_sig(subj31_clean, 6, "31", 35000)

```





















